# Generated by "setupctl update-pins" -- do not hand-edit, edits are overwritten.
# Both urls are vendor "latest" links, so hashes drift on every upstream build.
# Run "make update-pins" when darwin-rebuild reports a hash mismatch here.
{
  microsoftEdge = {
    version = "151.0.4129.93";
    url = "https://go.microsoft.com/fwlink/?linkid=2093504";
    hash = "sha256-CHTsaICGC/Mw+Q24hWAQrglzJGI9r0bUD4WQJXHfCCU=";
  };

  kumospace = {
    version = "6.1.0";
    url = "https://downloads.kumospace.com/production/macos/universal/latest/Kumospace.dmg";
    hash = "sha256-wOf4dabEIsJd5yHWXwlA/+lSrvz6ijVvZHLvswNZSas=";
  };
}
